config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :courses do
    resources :subjects
  end
  resources :user_subjects, only: :update
  namespace :admin do
    resources :users
    resources :subjects
    resources :user_subjects, only: :update
    resources :courses do
      resource :user_courses, only: [:show, :update]
    end
    resources :course_subjects
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<% provide :title, t("about") %>
<h1><%= t "about" %></h1>
<p>
  <%= t "description" %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, (t "contact") %>
<h1><%= t "contact" %></h1>
<p>
  <%= t "contact_detail" %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1><%= t "help" %></h1>
<p>
  <%= t "help_detail" %>
</p>

app/views/static_pages/home.html.erb
<div id="home_message_wrapper">
  <div class="row">
    <div class="col-md-12 welcome_message">
      <h1>
        <%= t "welcome_message" %>
      </h1>
      <% if logged_in? %>
        <nav id="colorNav">
          <ul>
            <li class="green">
              <%= link_to "", root_path, class: "glyphicon glyphicon-home" %>
              <ul>
                <li>
                  <%= link_to t("home.back_to_home"), root_path %>
                </li>
              </ul>
            </li>

            <% if current_user_is_admin? %>
              <li class="red">
                <%= link_to "", admin_users_path,
                  class: "glyphicon glyphicon-user" %>
                <ul>
                  <li>
                    <%= link_to t("home.user_list"), admin_users_path %>
                  </li>
                  <li>
                    <%= link_to t("home.add_new_list"), new_admin_user_path %>
                  </li>
                </ul>
              </li>
            <% end %>

            <li class="blue">
              <a href="#" class="glyphicon glyphicon-tags"></a>
              <ul>
                <li>
                  <% if current_user_is_admin? %>
                    <%= link_to t("home.browse_courses"), admin_courses_path %>
                  <% else %>
                    <%= link_to t("home.browse_courses"), courses_path %>
                  <% end %>
                </li>
                <% if current_user_is_admin? %>
                  <li>
                    <%= link_to t("home.add_new_course"),
                      new_admin_course_path %>
                  </li>
                <% end %>
              </ul>
            </li>

            <% if current_user_is_admin? %>
              <li class="yellow">
                <a href="#" class="glyphicon glyphicon-th-list"></a>
                <ul>
                  <li>
                    <%= link_to t("home.browse_subjects"),
                      admin_subjects_path %>
                  </li>
                  <li>
                    <%= link_to t("home.add_new_subject"),
                      new_admin_subject_path %>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </nav>
      <% else %>
        <h2>
          <%= link_to t("login"), login_path, id: "btn_login" %>
          <%= t "login_guide" %>
        </h2>
      <% end %>
    </div>
  </div>
</div>