config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :courses do
    resources :subjects
  end
  resources :user_subjects, only: :update
  namespace :admin do
    resources :users
    resources :subjects
    resources :user_subjects, only: :update
    resources :courses do
      resource :user_courses, only: [:show, :update]
    end
    resources :course_subjects
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :activities, dependent: :destroy
  has_many :user_courses
  has_many :courses, through: :user_courses
  has_many :user_subjects
  has_many :subjects, through: :user_subjects
  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  enum role: {trainee: 0, supervisor: 1, admin: 2}

  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def active_course
    user_course = user_courses.find &:is_active?
    user_course.try :course
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |user|
          csv << user.attributes.values_at(*column_names)
        end
      end
    end
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def remember
    remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_user, except: [:index, :create, :new]

  def index
    @users = User.order("created_at DESC")
      .paginate page: params[:page], per_page: Settings.pagination.size
    @all_users = User.all
    respond_to do |format|
      format.html
      format.csv {send_data @all_users.to_csv}
      format.xls
    end
  end

  def show
    @user_courses = UserCourse.by_user @user
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "flash.success.create_user"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = I18n.t "users.update.update_success"
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "flash.success.destroy_user"
    else
      flash[:danger] = t "flash.danger.destroy_user"
    end
    redirect_to admin_users_path
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = I18n.t "users.not_found"
      redirect_to admin_users_path
    end
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :role
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @active_course = @user.active_course
    @activities = @user.activities
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "users.update.update_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "users.not_found"
      redirect_to root_url
    end
  end

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/views/users/_active_course_info.html.erb
<div id="id_course_info_wrapper">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#home" aria-controls="home" role="tab" data-toggle="tab">
        <%= t "users.show.current_course_info" %>
      </a>
    </li>
    <li role="presentation">
      <a href="#activities" aria-controls="activities" role="tab"
        data-toggle="tab">
        <%= t "users.show.activities_list" %>
      </a>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
      <div id="id_course_info">
        <% if @active_course.nil? %>
          <h2>
            <%= t "users.show.user_has_no_course" %>
          </h2>
        <% else %>
          <h2>
            <%= t "users.show.course_info" %>
          </h2>
          <%= render "admin/courses/course_item",
            course: @active_course %>

          <h2>
            <%= t"users.show.subjects_list" %>
          </h2>
          <div id="id_subject_list_wrapper">
            <div id="id_subjects_list">
              <% if @active_course.subjects.nil? ||
                @active_course.subjects.empty? %>
                <p class="margin_bottom_10px">
                  <%= t "users.show.course_has_no_subject" %>
                </p>
              <% else %>
                <%= render partial: "subjects_list",
                  collection: @active_course.subjects, as: "subject",
                  locals: {course: @active_course} %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="activities">
      <div id="id_activities_wrapper">
        <h2>
          <%= t "users.show.activities_list" %>
        </h2>
        <% if @activities.any? %>
          <ul>
            <%= render @activities %>
          </ul>
        <% else %>
          <%= t "activity.none" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title center"><%= @user.name %></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-3 col-lg-3 " align="center">
                <%= gravatar_for @user, {size: Settings.avatar.large_size} %>
              </div>
              <div class=" col-md-9 col-lg-9 ">
                <table class="table table-user-information">
                  <tbody>
                    <tr>
                      <td><%= t ".email" %></td>
                      <td><%= @user.email %></td>
                    </tr>
                    <tr>
                      <td><%= t ".created_date" %></td>
                      <td><%= @user.created_at.strftime("%c") %></td>
                    </tr>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <%= mail_to @user.email, class: "btn btn-sm btn-primary" do %>
            <i class="glyphicon glyphicon-envelope"></i>
            <%= t ".send_mail" %>
          <% end %>
          <span class="pull-right">
            <% if current_user? @user %>
              <%= link_to edit_user_path(@user),
                class: "btn btn-sm btn-warning" do %>
                <i class="glyphicon glyphicon-edit"></i>
                <%= t ".edit_button" %>
              <% end %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to edit_admin_user_path(@user),
                class: "btn btn-sm btn-danger" do %>
                <i class="glyphicon glyphicon-edit"></i>
                <%= t ".edit_admin_button" %>
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>


<%= render "active_course_info" %>

app/views/users/_subjects_list.html.erb
<% user_subject = get_user_subject current_user, subject, course.id %>
<div class="panel-group" role="tablist">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="id_subject_<%= subject.id %>">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#id_subjects_list"
          href="#id_tasks_<%= subject.id %>" aria-expanded="true"
          aria-controls="id_tasks_<%= subject.id %>">
          <%= subject.name %>
        </a>
        <%= render "shared/status_label", status: user_subject&.status %>
      </h4>
    </div>
    <div id="id_tasks_<%= subject.id %>" class="panel-collapse collapse"
      role="tabpanel" aria-labelledby="id_subject_<%= subject.id %>">
        <ul class="list-group">
          <% subject.tasks.each do |task| %>
            <li class="list-group-item">
              <%= task.name %>
              <% if user_subject %>
                <% user_task = user_subject.user_tasks
                  .by_task(task.id).first  %>
                <% if user_task %>
                  <p class="label label-success pull-right">
                    <%= t "task_status.finished" %>
                  </p>
                <% else %>
                  <p class="label label-danger pull-right">
                    <%= t "tast_status.unfinished" %>
                  </p>
                <% end %>
              <% end %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save_button") %>
<h1><%= t ".header_text" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">
        <%= t ".change_button"  %>
      </a>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <%= render "show" %>
</div>