config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :courses do
    resources :subjects
  end
  resources :user_subjects, only: :update
  namespace :admin do
    resources :users
    resources :subjects
    resources :user_subjects, only: :update
    resources :courses do
      resource :user_courses, only: [:show, :update]
    end
    resources :course_subjects
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :course_subjects
  has_many :courses, through: :course_subjects
  has_many :user_subjects
  has_many :users, through: :user_subjects
  has_many :tasks

  validates :name, presence: true
  validates :instructions, presence: true

  accepts_nested_attributes_for :tasks, allow_destroy: true,
    reject_if: proc {|a| a[:name].blank?}

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :logged_in_user, :verify_admin_and_supervisor
  before_action :load_subject, except: [:index, :new, :create]

  include SubjectsHelper

  def index
    @subjects = Subject.paginate page: params[:page]
  end

  def new
    @subject = Subject.new
    @subject.tasks.build
  end

  def show
    @tasks = @subject.tasks
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t "flash.success.create_subject"
      redirect_to admin_subjects_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    session[:return_to] ||= request.referer
    if @subject.update_attributes subject_params
      flash[:success] = t "flash.success.update_subject"
      redirect_to session.delete(:return_to)
    else
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t "flash.success.delete_subject"
    else
      flash[:error] = t "flash.error.delete_subject"
    end
    redirect_to admin_subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit :name, :instructions,
      tasks_attributes: [:id, :name, :_destroy]
  end

  def load_subject
    @subject = Subject.find_by id: params[:id]
    unless @subject
      flash[:danger] = t "admin.subjects.not_found"
      redirect_to admin_subjects_path
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :load_subject, only: [:show, :update]

  include SubjectsHelper

  def show
    @tasks = @subject.tasks
    @activities = current_user.activities
      .by_target Settings.activity.target_type.subject, @subject.id
    @user_tasks = Task.by_user current_user
    @user_subject.build_user_tasks current_user, @user_tasks
  end

  def update
    session[:return_to] ||= request.referer
    if @user_subject.update_attributes user_subject_params
      flash[:success] = t "flash.success.report_updated"
      redirect_to session.delete(:return_to)
    else
      flash[:danger] = t "flash.danger.report_updated"
      redirect_to courses_path
    end
  end

  private
  def load_subject
    @subject = Subject.find_by id: params[:id]
    @course = Course.find_by id: params[:course_id]
    unless @subject && current_user.subjects.include?(@subject) && @course
      flash[:danger] = t ".not_found"
      redirect_to courses_path
    end
    @user_subject = get_user_subject current_user, @subject, @course.id
  end

  def user_subject_params
    params.require(:user_subject).permit :status,
      user_tasks_attributes: [:user_id, :task_id]
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def get_user_subject user, subject, course_id
    user.user_subjects.by_course_subject(course_id, subject).first
  end
end

app/views/subjects/_subject.html.erb
<% user_subject = get_user_subject current_user, subject, course.id %>
<div class="masonry-item">
  <div class="panel panel-info">
    <div class="panel-heading">
      <%= render "shared/status_label",
        status: user_subject.status if user_subject %>
      <%= subject.name %>
    </div>
    <div class="panel-body">
      <%= subject.instructions %>
    </div>
    <div class="panel-footer">
      <% if user_subject %>
        <%= link_to course_subject_path(course, subject),
          class: "btn btn-primary" do %>
          <i class="glyphicon glyphicon-search"></i>
          <%= t "courses.btnView" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/subjects/show.html.erb
<%= provide :title, @subject.name %>
<h1><%= @subject.name %></h1>
<div class="panel panel-success">
  <div class="panel-heading">
    <%= render "shared/status_label", status: @user_subject.status %>
    <p><%= t ".instructions" %></p>
  </div>
  <div class="panel-body">
    <div class="course_instruction">
      <%= @subject.instructions %>
    </div>
  </div>
</div>
<div class="panel panel-success">
  <div class="panel-heading">
    <%= t ".tasks_in_subject" %>
  </div>
  <%= form_for @user_subject, url: course_subject_path(@course, @subject) do |f| %>
    <div class="panel-body">
      <div class="masonry">
        <%= f.fields_for :user_tasks do |builder| %>
          <div class="masonry-item">
            <div class="panel panel-info">
              <div class="panel-heading">
                <%= builder.object.task.name %>
              </div>
              <div class="panel-body">
                <%= builder.object.task.content %>
              </div>
              <div class="panel-footer">
                <% if builder.object.persisted? %>
                  <p class="label label-danger"><%= t ".finished_label" %></p>
                <% else %>
                  <% if @user_subject.started? %>
                    <%= builder.check_box :task_id, {checked: builder.object
                      .persisted?}, builder.object.task.id, nil %>
                    <p class="label label-warning">
                      <%= t ".finish_question" %>
                    </p>
                    <%= builder.hidden_field :user_id,
                      value: current_user.id %>
                  <% else %>
                    <p class="label label-default"><%= t ".not_finish" %></p>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="panel-footer">
      <% if @user_subject.started? %>
        <%= f.submit t(".report_button"), class: "btn btn-primary" %>
        <span class="pull-right">
          <span class="label label-danger"><%= t ".finish_question" %></span>
          <%= f.check_box :status, {checked: false,
            class: "checkbox-inline"}, Settings.status.finished_text, nil %>
        </span>
      <% end %>
    </div>
  <% end %>
</div>
<div class="panel panel-warning">
  <div class="panel-heading">
    <%= t "activity.title" %>
  </div>
  <div class="panel-body container">
    <% if @activities.any? %>
      <%= render @activities, object: @subject %>
    <% else %>
      <%= t "activity.none" %>
    <% end %>
  </div>
</div>