config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :courses do
    resources :subjects
  end
  resources :user_subjects, only: :update
  namespace :admin do
    resources :users
    resources :subjects
    resources :user_subjects, only: :update
    resources :courses do
      resource :user_courses, only: [:show, :update]
    end
    resources :course_subjects
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :activities, dependent: :destroy
  has_many :user_courses
  has_many :courses, through: :user_courses
  has_many :user_subjects
  has_many :subjects, through: :user_subjects
  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  enum role: {trainee: 0, supervisor: 1, admin: 2}

  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def active_course
    user_course = user_courses.find &:is_active?
    user_course.try :course
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |user|
          csv << user.attributes.values_at(*column_names)
        end
      end
    end
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def remember
    remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_user, except: [:index, :create, :new]

  def index
    @users = User.order("created_at DESC")
      .paginate page: params[:page], per_page: Settings.pagination.size
    @all_users = User.all
    respond_to do |format|
      format.html
      format.csv {send_data @all_users.to_csv}
      format.xls
    end
  end

  def show
    @user_courses = UserCourse.by_user @user
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "flash.success.create_user"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = I18n.t "users.update.update_success"
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "flash.success.destroy_user"
    else
      flash[:danger] = t "flash.danger.destroy_user"
    end
    redirect_to admin_users_path
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = I18n.t "users.not_found"
      redirect_to admin_users_path
    end
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :role
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @active_course = @user.active_course
    @activities = @user.activities
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "users.update.update_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "users.not_found"
      redirect_to root_url
    end
  end

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @user] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :role %><div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :role %>
        <%= f.select :role, Settings.role, {}, {class: "form-control"} %>
      </div>
      <%= f.submit (t ".submit_button"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/users/_show.html.erb
<div class="row">
  <div class="toppad col-xs-12 col-md-12 col-sm-12" >
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title center"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 col-lg-3 " align="center">
            <%= gravatar_for @user, {size: Settings.avatar.large_size} %>
          </div>
          <div class=" col-md-9 col-lg-9 ">
            <table class="table table-user-information">
              <tbody>
                <tr>
                  <td><%= t "admin.users.index.txt_Email" %></td>
                  <td><%= @user.email %></td>
                </tr>
                <tr>
                  <td><%= t "admin.users.index.txt_Created_At" %></td>
                  <td>
                    <%= @user.created_at.strftime(t "time_format") %>
                  </td>
                </tr>
                <tr>
                  <td><%= t "admin.users.index.txt_Role" %></td>
                  <td>
                    <span class="label label-danger"><%= @user.role %></span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <%= mail_to @user.email, class: "btn btn-sm btn-primary" do %>
          <i class="glyphicon glyphicon-envelope"></i>
          <%= t ".send_mail" %>
        <% end %>
        <span class="pull-right">
          <% if current_user?(@user) || @user.trainee? %>
            <%= link_to edit_admin_user_path(@user),
              class: "btn btn-sm btn-warning" do %>
              <i class="glyphicon glyphicon-edit"></i>
              <%= t "admin.users.index.btn_Edit" %>
            <% end %>
          <% end %>
          <% if @user.trainee? %>
            <%= link_to admin_user_path(@user), method: :delete, data:
              {confirm: t("msg_confirm_delete")},
              class: "btn btn-sm btn-danger" do %>
              <i class="glyphicon glyphicon-remove"></i>
              <%= t "admin.users.index.btn_Delete" %>
            <% end %>
          <% end %>
        </span>
      </div>
    </div>
    <div class="panel panel-success">
      <div class="panel-heading">
      <h4 class="panel-title"><%= t ".user_course", name: @user.name %></h4>
      </div>
      <div class="panel-body">
        <%= render @user_courses %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/_user_all.html.erb
<table class="table table-hover table-bordered table-striped">
  <thead class="bg-primary">
    <tr>
      <th class="center width_50_px"><%= t "admin.users.index.txt_index" %></th>
      <th class="center"><%= t "admin.users.index.txt_Name" %></th>
      <th class="center"><%= t "admin.users.index.txt_Email" %></th>
      <th class="center width_70_px"><%= t "admin.users.index.txt_Role" %></th>
      <th class="center width_200_px"><%= t "admin.users.index.txt_Created_At" %></th>
      <th class="center width_240_px" colspan="3"><%= "Action" %> </th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "user_item", collection: @users, as: "user" %>
  </tbody>
</table>

app/views/admin/users/_user_item.html.erb
<tr>
  <td class="center"><%= get_pagination_element_index @users, user %></td>
  <td><%= link_to user.name, user %></td>
  <td><%= user.email %></td>
  <td><%= user.role.capitalize %></td>
  <td><%= user.created_at.strftime(t "time_format") %></td>
  <td class="center">
    <%= link_to admin_user_path(user), remote: true, data: {toggle: "modal", target: "#myModal"} do %>
      <span class="glyphicon glyphicon-search"></span>
      <%= t "admin.users.index.btn_View" %>
    <% end %>
  </td>
  <td class="center">
    <%= link_to edit_admin_user_path(user) do %>
      <span class="glyphicon glyphicon-edit"></span>
      <%= t "admin.users.index.btn_Edit" %>
    <% end %>
  </td>
  <% if current_user? user %>
    <td></td>
  <% else %>
    <td class="center">
      <%= link_to admin_user_path(user), method: :delete, data:
        {confirm: t("msg_confirm_delete")}, class: "text-danger" do %>
        <span class="glyphicon glyphicon-remove"></span>
        <%= t "admin.users.index.btn_Delete" %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/admin/users/edit.html.erb
<h1><%= t ".title" %></h1>
<%= render "form" %>

app/views/admin/users/index.html.erb
<div class="panel-header">
  <div class="label label-warning pull-right">
    <%= t ".export" %>
    <%= link_to t(".export_csv"), admin_users_path(format: "csv") %> |
    <%= link_to t(".export_xls"), admin_users_path(format: "xls") %>
  </div>
  <span class="pull-left margin_bottom_10px">
    <% unless current_user.trainee? %>
      <%= link_to new_admin_user_path,
        class: "btn btn-primary" do %>
        <i class="glyphicon glyphicon-new"></i>
        <%= t "admin.users.index.btn_New" %>
      <% end %>
    <% end %>
  </span>
</div>
<div id="list-users">
  <%= render "user_all" %>
  <%= will_paginate %>
</div>
<div id="myModal" class="modal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
      </div>
      <div class="modal-body">
        <div id="user-show"></div>
      </div>
      <div class="modal-footer">
        <a data-dismiss="modal" class="btn btn-success confirm">
          <%= t "btnOK" %>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Users">
    <Table>
      <Row>
        <Cell>
          <Data ss:Type="String"><%= t "admin.users.xls.id" %></Data>
        </Cell>
        <Cell>
          <Data ss:Type="String"><%= t "admin.users.xls.name" %></Data>
        </Cell>
        <Cell>
          <Data ss:Type="String"><%= t "admin.users.xls.email" %></Data>
        </Cell>
        <Cell>
          <Data ss:Type="String"><%= t "admin.users.xls.role" %></Data>
        </Cell>
        <Cell>
          <Data ss:Type="String"><%= t "admin.users.xls.created_at" %></Data>
        </Cell>
      </Row>
    <% @all_users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= user.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.role %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= user.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/users/new.html.erb
<h1><%= t ".title" %></h1>
<%= render "form" %>

app/views/admin/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <%= render "show"%>
</div>

app/views/admin/users/show.js.erb
$("#user-show").html("<%= j render 'show' %>");